name: Build Executables

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            executable: PumpkinScheduler.exe
            asset_name: PumpkinScheduler-Windows.zip
          - os: macos-latest
            executable: PumpkinScheduler
            asset_name: PumpkinScheduler-macOS.zip
          - os: ubuntu-latest
            executable: PumpkinScheduler
            asset_name: PumpkinScheduler-Linux.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        python build_exe.py
      env:
        CI: true

    - name: Create release package
      run: |
        python create_release.py
      env:
        CI: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: release/PumpkinScheduler-Release.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Rename release files
      run: |
        mv "artifacts/PumpkinScheduler-Windows.zip/PumpkinScheduler-Release.zip" "PumpkinScheduler-Windows.zip"
        mv "artifacts/PumpkinScheduler-macOS.zip/PumpkinScheduler-Release.zip" "PumpkinScheduler-macOS.zip"
        mv "artifacts/PumpkinScheduler-Linux.zip/PumpkinScheduler-Release.zip" "PumpkinScheduler-Linux.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          PumpkinScheduler-Windows.zip
          PumpkinScheduler-macOS.zip
          PumpkinScheduler-Linux.zip
        body: |
          ## 🎃 PumpkinScheduler Release
          
          ### ✨ What's New
          - User-friendly time selectors (no cron knowledge needed!)
          - System tray integration for background operation
          - Auto-generated encryption keys (no manual setup!)
          - Cross-platform executables ready to run
          
          ### 📦 Downloads
          - **Windows**: PumpkinScheduler-Windows.zip
          - **macOS**: PumpkinScheduler-macOS.zip  
          - **Linux**: PumpkinScheduler-Linux.zip
          
          ### 🚀 Quick Start
          1. Download the zip for your platform
          2. Extract and run PumpkinScheduler
          3. No additional setup required!
          
          Perfect for Minecraft and Palworld server automation! 🎮
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
